[project]
name = "crewai-business-consultant"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "crewai>=0.177.0",
    "langchain-cohere>=0.4.5",
    "streamlit>=1.49.1",
]
